vim.keymap.set("t", "<c-[>", "<Esc>", { buffer = 0, desc = "Pass ESC to Claude" })
vim.keymap.set({"n", "i"}, "<C-h>", function() require("herdr").move("h") end, { buffer = 0, desc = "Move focus to the left window" })
vim.keymap.set({"n", "i"}, "<C-l>", function() require("herdr").move("l") end, { buffer = 0, desc = "Move focus to the right window" })
vim.keymap.set({"n", "i"}, "<C-j>", "<C-w><C-j>", { buffer = 0, desc = "Move focus to the lower window" })
vim.keymap.set({"n", "i"}, "<C-k>", "<C-w><C-k>", { buffer = 0, desc = "Move focus to the upper window" })
