require("user.impatient")
require("user.options")
require("user.keymaps")
require("user.plugins")

require("user.lsp-zero")
require("user.colorscheme")
require("user.mason")
require("user.cmp")
require("user.lsp")
require("user.lsp.null-ls")

require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.gitsigns")
require("user.fugitive")
require("user.nvim-tree")
require("user.lualine")
require("user.luasnip")
require "user.toggleterm"
require("user.indentline")
require("user.vimwiki")
require("user.autocommands")
require("user.vim-test")
require("user.tmux-nav")

require("user.nvim-dap")

require("user.nvim-lint")
require("user.telekasten")
