require("user.impatient")
require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.colorscheme")
require("user.cmp")
require("user.lsp")

require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.gitsigns")
require("user.fugitive")
require("user.nvim-tree")
require("user.lualine")
require "user.toggleterm"
require("user.indentline")
require("user.vimwiki")
require("user.autocommands")
require("user.vim-test")

require("user.nvim-dap")

require("user.nvim-lint")
