#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.33
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  00
yabai -m config bottom_padding               00
yabai -m config left_padding                 00
yabai -m config right_padding                00
yabai -m config window_gap                   06

yabai -m rule --add app="^Tandem$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^DBngin$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Purk$" manage=off
yabai -m rule --add app="^JetBrains Toolbox$" manage=off
yabai -m rule --add app="^Flux$" manage=off
yabai -m rule --add app="^Installer$" manage=off
yabai -m rule --add app="^System Information$" manage=off

yabai -m rule --add app="^Brave Browser$" space=1
yabai -m rule --add app="^iTerm2$" space=2
yabai -m rule --add app="^WezTerm$" space=2
yabai -m rule --add app="^Alacritty$" space=2
yabai -m rule --add app="^Workplace Chat$" space=3
yabai -m rule --add app="^WhatsApp$" space=3
yabai -m rule --add app="^TablePlus$" space=4
yabai -m rule --add app="^DBngin$" space=4
yabai -m rule --add app="^Spotify$" space=5
yabai -m rule --add app="^Sonos$" space=5
yabai -m rule --add app="^PhpStorm$" space=6
yabai -m rule --add app="^Google Chrome$" space=6

# Move calls to space 6
yabai -m rule --add app="^Workplace Chat$" title="Workplace Call" space=6

# yabai -m rule --add app="^Phpstorm$" manage=off

# yabai -m rule --add app="^PhpStorm$" manage=off
# PhpStorm is sneaky it uses char 0x2013 as the dash, which is EN Dash
 # yabai -m rule --add app="^PhpStorm$" title="^.*–" manage=off
 yabai -m rule --add app="Workplace Chat" title="Media Viewer" manage=off
yabai -m rule --add app="^PhpStorm$" title="Push Commits" manage=off
yabai -m rule --add app="^PhpStorm$" title="Preferences" manage=off
yabai -m rule --add app="^PhpStorm$" title="^Pull to.*" manage=off
yabai -m rule --add app="^PhpStorm$" title="^Commit Changes" manage=off
yabai -m rule --add app="^TablePlus$" manage=off

yabai -m config --space 4 layout float

echo "yabai configuration loaded.."
